<!DOCTYPE html>
<html>
<head>
	<title>Plantilla</title>
	

    <!-- Mobile Specifics --> 

<!-- Mobile Internet Explorer ClearType Technology -->
<!--[if IEMobile]>  <meta http-equiv="cleartype" content="on">  <![endif]-->

<!-- Bootstrap -->

<!-- Main Style -->
<link href="_include/css/main.css" rel="stylesheet">

<!-- Supersized -->
<link href="_include/css/supersized.css" rel="stylesheet">
<link href="_include/css/supersized.shutter.css" rel="stylesheet">

<!-- FancyBox -->
<link href="_include/css/fancybox/jquery.fancybox.css" rel="stylesheet">

<!-- Font Icons -->
<link href="_include/css/fonts.css" rel="stylesheet">

<!-- Shortcodes -->

<!-- Responsive -->
<link href="_include/css/bootstrap-responsive.min.css" rel="stylesheet">
<link href="_include/css/responsive.css" rel="stylesheet">

<!-- Supersized -->

<!-- Google Font -->

<!-- Fav Icon -->
<link rel="shortcut icon" href="#">


<!-- Modernizr -->

<!-- Analytics -->
<!-- End Analytics -->

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


	<!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- Our Custom CSS -->
    <link rel="stylesheet" href="style/estilo.css">
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">
</head>
<body>
	<script>
		
		function Musica(){
			window.location="index3.html";
		}
	</script>

	<div class="wrapper">
            <!-- Sidebar Holder -->
            <nav id="sidebar">
                <div class="sidebar-header">
                    <center><h3>Foto del Usuario</h3></center>	
                </div>

                <ul class="list-unstyled components">
                    <center><p>Nombre del Usuario</p></center>
                    <li class="active">
                        <a>Inicio</a>
                    </li>
                    <li>
                        <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" onclick = Musica()>Musica</a>
                        <ul class="collapse list-unstyled" id="pageSubmenu">
                            <li><a href="#">Album</a></li>
                            <li><a href="#">Artistas</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#">Videos</a>
                    </li>
                    <li>
                        <a href="#">Contact</a>
                    </li>
                </ul>

                <ul class="list-unstyled CTAs">
                    <li><a href="https://bootstrapious.com/tutorial/files/sidebar.zip" class="download">Download source</a></li>
                    <li><a href="https://bootstrapious.com/p/bootstrap-sidebar" class="article">Back to article</a></li>
                </ul>
            </nav>

            <!-- Contenido de la pagina -->
            <div id="content">

				<div class="row">
		        	<div class="span3">
		            	<!-- Filter -->
		                
		                <!-- End Filter -->
		            </div>
		            
		            <div class="span9">
		            	<div class="row">
		                	<section id="projects">
		                    	<ul id="thumbs">
		                        
									<!-- Item Project and Filter Name -->
		                        	<li class="item-thumbs span3 design">
		                            	<!-- Fancybox - Gallery Enabled - Title - Full Image -->
		                            	<a class="hover-wrap fancybox" data-fancybox-group="gallery" title="The City" href="_include/img/work/full/image-01-full.jpg">
		                                	<span class="overlay-img"></span>
		                                    <span class="overlay-img-thumb font-icon-plus"></span>
		                                </a>
		                                <!-- Thumb Image and Description -->
		                                <img src="_include/img/work/thumbs/image-01.jpg" alt="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus quis elementum odio. Curabitur pellentesque, dolor vel pharetra mollis.">
		                            </li>
		                        	<!-- End Item Project -->
		                            
									<!-- Item Project and Filter Name -->
		                        	<li class="item-thumbs span3 design">
		                            	<!-- Fancybox - Gallery Enabled - Title - Full Image -->
		                            	<a class="hover-wrap fancybox" data-fancybox-group="gallery" title="The Office" href="_include/img/work/full/image-02-full.jpg">
		                                	<span class="overlay-img"></span>
		                                    <span class="overlay-img-thumb font-icon-plus"></span>
		                                </a>
		                                <!-- Thumb Image and Description -->
		                                <img src="_include/img/work/thumbs/image-02.jpg" alt="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus quis elementum odio. Curabitur pellentesque, dolor vel pharetra mollis.">
		                            </li>
		                        	<!-- End Item Project -->
		                            
									<!-- Item Project and Filter Name -->
		                        	<li class="item-thumbs span3 photography">
		                            	<!-- Fancybox - Gallery Enabled - Title - Full Image -->
		                            	<a class="hover-wrap fancybox" data-fancybox-group="gallery" title="The Mountains" href="_include/img/work/full/image-03-full.jpg">
		                                	<span class="overlay-img"></span>
		                                    <span class="overlay-img-thumb font-icon-plus"></span>
		                                </a>
		                                <!-- Thumb Image and Description -->
		                                <img src="_include/img/work/thumbs/image-03.jpg" alt="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus quis elementum odio. Curabitur pellentesque, dolor vel pharetra mollis.">
		                            </li>
		                        	<!-- End Item Project -->
		                            
									<!-- Item Project and Filter Name -->
		                        	<li class="item-thumbs span3 video">
		                            	<!-- Fancybox Media - Gallery Enabled - Title - Link to Video -->
		                            	<a class="hover-wrap fancybox-media" data-fancybox-group="video" title="Video Content From Vimeo" href="http://vimeo.com/51460511">
		                                	<span class="overlay-img"></span>
		                                    <span class="overlay-img-thumb font-icon-plus"></span>
		                                </a>
		                                <!-- Thumb Image and Description -->
		                                <img src="_include/img/work/thumbs/image-08.jpg" alt="Video">
		                            </li>
		                        	<!-- End Item Project -->
		                            
									<!-- Item Project and Filter Name -->
		                        	<li class="item-thumbs span3 photography">
		                            	<!-- Fancybox - Gallery Enabled - Title - Full Image -->
		                            	<a class="hover-wrap fancybox" data-fancybox-group="gallery" title="The Sea" href="_include/img/work/full/image-04-full.jpg">
		                                	<span class="overlay-img"></span>
		                                    <span class="overlay-img-thumb font-icon-plus"></span>
		                                </a>
		                                <!-- Thumb Image and Description -->
		                                <img src="_include/img/work/thumbs/image-04.jpg" alt="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus quis elementum odio. Curabitur pellentesque, dolor vel pharetra mollis.">
		                            </li>
		                        	<!-- End Item Project -->
		                            
									<!-- Item Project and Filter Name -->
		                        	<li class="item-thumbs span3 photography">
		                            	<!-- Fancybox - Gallery Enabled - Title - Full Image -->
		                            	<a class="hover-wrap fancybox" data-fancybox-group="gallery" title="Clouds" href="_include/img/work/full/image-05-full.jpg">
		                                	<span class="overlay-img"></span>
		                                    <span class="overlay-img-thumb font-icon-plus"></span>
		                                </a>
		                                <!-- Thumb Image and Description -->
		                                <img src="_include/img/work/thumbs/image-05.jpg" alt="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus quis elementum odio. Curabitur pellentesque, dolor vel pharetra mollis.">
		                            </li>
		                        	<!-- End Item Project -->
		                            
									<!-- Item Project and Filter Name -->
		                        	<li class="item-thumbs span3 video">
		                            	<!-- Fancybox Media - Gallery Enabled - Title - Link to Video -->
		                            	<a class="hover-wrap fancybox-media" data-fancybox-group="video" title="Video Content From Vimeo" href="videos/ReZero.mp4">
		                                    <span class="overlay-img-thumb font-icon-play"></span>
		                                </a>
		                                <!-- Thumb Image and Description -->
		                                <img src="_include/img/reZero.jpg" class="">
		                            </li>
		                        	<!-- End Item Project -->
		                            
									<!-- Item Project and Filter Name -->
		                        	<li class="item-thumbs span3 design">
		                            	<!-- Fancybox - Gallery Enabled - Title - Full Image -->
		                            	<a class="hover-wrap fancybox" data-fancybox-group="gallery" title="The Dark" href="_include/img/work/full/image-06-full.jpg">
		                                	<span class="overlay-img"></span>
		                                    <span class="overlay-img-thumb font-icon-plus"></span>
		                                </a>
		                                <!-- Thumb Image and Description -->
		                                <img src="_include/img/work/thumbs/image-06.jpg" alt="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus quis elementum odio. Curabitur pellentesque, dolor vel pharetra mollis.">
		                            </li>
		                        	<!-- End Item Project -->
		                            
									<!-- Item Project and Filter Name -->
		                        	<li class="item-thumbs span3 design">
		                            	<!-- Fancybox - Gallery Enabled - Title - Full Image -->
		                            	<a class="hover-wrap fancybox" data-fancybox-group="gallery" title="The Beach" href="_include/img/work/full/image-07-full.jpg">
		                                	<span class="overlay-img"></span>
		                                    <span class="overlay-img-thumb font-icon-plus"></span>
		                                </a>
		                                <!-- Thumb Image and Description -->
		                                <img src="_include/img/work/thumbs/image-07.jpg" alt="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus quis elementum odio. Curabitur pellentesque, dolor vel pharetra mollis.">
		                            </li>
		                        	<!-- End Item Project -->
		                        </ul>
		                    </section>
		                    
		            	</div>
		            </div>
		        </div>

				





                <h2>Videos Mas Vistos</h2>
                <video src="videos/ReZero.mp4" width="560" height="315" preload="preload" controls="controls"></video>
                <p>Lorem ipsum </p>

                <div class="line"></div>

                <h2>Musicas Mas Escuchadas</h2>
                <audio src="musicas/bahamut.mp3" controls="controls"></audio>
                <p>Lorem ipsum.</p>

                <div class="line"></div>

                <h3>Lorem Ipsum Dolor</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            
            </div>
        </div>





        <!-- jQuery CDN -->
        <script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
        <!-- Bootstrap Js CDN -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <!-- jQuery Custom Scroller CDN -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>
		
		



</body>
</html>